//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgramskoIntenjerstvo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Izdatnica
    {
        public int id_izdatnica { get; set; }
        public System.DateTime datum_vrijeme { get; set; }
        public int id_namirnica { get; set; }
        public double kolicina { get; set; }
        public int id_mjerna_jedinica { get; set; }
    
        public virtual Mjerna_jedinica Mjerna_jedinica { get; set; }
        public virtual Namirnica Namirnica { get; set; }
    }
}
