//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgramskoIntenjerstvo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Na_meniju
    {
        public int id_meni { get; set; }
        public int id_jelo { get; set; }
        public Nullable<int> entityframeowrkfix { get; set; }
    
        public virtual Jelo Jelo { get; set; }
        public virtual Meni Meni { get; set; }
    }
}
