//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgramskoIntenjerstvo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Namirnica
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Namirnica()
        {
            this.Jelo_sadrzi = new HashSet<Jelo_sadrzi>();
            this.Stanje_zaliha = new HashSet<Stanje_zaliha>();
        }
    
        public int id_namirnica { get; set; }
        public string naziv_namirnice { get; set; }
        public int id_kategorije { get; set; }
        public double temperatura_pohrane { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Jelo_sadrzi> Jelo_sadrzi { get; set; }
        public virtual Kategorija Kategorija { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stanje_zaliha> Stanje_zaliha { get; set; }
    }
}
