//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgramskoIntenjerstvo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Primka
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Primka()
        {
            this.Stavke_primke = new HashSet<Stavke_primke>();
        }
    
        public int id_primka { get; set; }
        public System.DateTime datum_vrijeme { get; set; }
        public int id_namirnica { get; set; }
        public double kolicina { get; set; }
        public int id_mjerna_jedinica { get; set; }
    
        public virtual Mjerna_jedinica Mjerna_jedinica { get; set; }
        public virtual Namirnica Namirnica { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stavke_primke> Stavke_primke { get; set; }
    }
}
