//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgramskoIntenjerstvo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stavke_izdatnice
    {
        public int id_izdatnica { get; set; }
        public int id_namirnica { get; set; }
        public double kolicina_izdavanja { get; set; }
    }
}
