//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgramskoIntenjerstvo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stol
    {
        public int id_stol { get; set; }
        public string opis { get; set; }
        public int broj_mjesta { get; set; }
        public bool rezerviran { get; set; }
    }
}
